### PR TITLE
HACDOCS-264-Correction-3: Learn more copy: Link to repo or start with code sample

### PR DESCRIPTION
**Pull request by jseseCCS**
fixing bad formatting on lists, notes

[HACDOCS-264](https://issues.redhat.com/browse/HACDOCS-264)

### CODE REVIEW

**Comment by jseseCCS** [comment]
@christianvogt can you take a look at this for me?

**Comment by christianvogt** [comment]
Changes to fix the formatting of lists looks good in the preview.
/lgtm

**Comment by jseseCCS** [comment]
thanks so much again, @christianvogt! someone will merge this when the checks finish?

**Pull request merged**
