### PR TITLE
adding a warning about env vars

### PR DESCRIPTION
**Pull request by missmesss**
HACDOCS-446: Users shouldn't store secrets as env vars, adding a warning about that.

### CODE REVIEW

**Comment by missmesss** [comment]
@amfred Do you think this 1 line about env vars will be sufficient?
This warning will appear in side panel (in-app) help, and I hope UX will be able to extend the "Env vars" pop-over text too, I contacted them.
Thanks!

**Review by amfred — APPROVED** [review]

**Comment by amfred** [comment]
I think one line is sufficient, thanks!

**Review by jc-berger — APPROVED** [review]
/lgtm

**Comment by missmesss** [comment]
@Hyperkid123 Both reviews are complete, will you please check and merge this PR? Thanks!

**Review by Hyperkid123 — APPROVED** [review]

**Pull request merged**
