### PR TITLE
HACDOCS-510: Updating Config components Learn more to include Add secret

### PR DESCRIPTION
**Pull request by jseseCCS**
Per [HACDOCS-510](https://issues.redhat.com/browse/HACDOCS-510), adding info to **Learn more** side panel help for **Config components** to include **Add secret**.

### CODE REVIEW

**Comment by jseseCCS** [comment]
hi, @karthikjeeyar! i added content about adding a build secret, and i also made a few tiny tweaks related to UI updates since my last PR for this content. can you give me your SME review?

**Review by karthikjeeyar — APPROVED** [review]
/lgtm

**Comment by jseseCCS** [comment]
@Hyperkid123 can you get this pubbed at your earliest convenience? :pray:

**Pull request merged**
