### PR TITLE
Drafted Create app panel

### PR DESCRIPTION
**Pull request by missmesss**
@Hyperkid123 Hi Martin, will you please review the text here? I wonder whether an ordered Markdown list would be rendered correctly (as it relies on indentations same as yaml).

Will using multiline strings blocks (scalars) help? I'm not sure Markdown will work inside them...

In the ideal world, we hoped to get a mixed list here, but I'm afraid it'll require too many spaces and won't be rendered in the end. Is there a way of getting something like that in App Studio side panels?

1. **GitHub repository**

   App Studio can build apps written in the following languages:
    - Python
    - Java
    - Go
    - Node.js
    
   To get started, add a URL of your GitHub repo. Then, we’ll fetch your code, build a container image for you, and deploy it.
       
1. **Quay container image**

Thank you in advance for any help or tips.

### CODE REVIEW

**Comment by Hyperkid123** [comment]
@missmesss this is how the help topic looks in the UI. The content looks ok to me.

screenshot-stage foo redhat com_1337-2022 06 07-10_30_56

**Comment by missmesss** [comment]
@Hyperkid123 Thank you so much for the screenshot, it helps a lot!

I'm wondering whether there's a way for writers to get the previews for similar future PRs? I assume it's not really possible at the moment? I just hate thinking how many more screenshots you'd have to create for us to help us out...

I'll add 1 more commit here before a merge. Thank you.

**Comment by Hyperkid123** [comment]
@missmesss we could ask @CooperRedhat to provide some online too to use for previews. Maybe include it into the docs here: https://quickstarts.netlify.app/in-context-help

So you can just dump the content in it and see the output.

**Comment by Hyperkid123** [comment]
closing in favor of #27

**Pull request closed without merging**
