### PR TITLE
Adding HMS tile

### PR DESCRIPTION
**Pull request by elianerpereira**
Creating this PR to request adding the HMS tile to Insights.
@Hyperkid123

### CODE REVIEW

**Comment by elianerpereira** [comment]
JIRA: https://issues.redhat.com/browse/RHCLOUD-26004

**Comment by Hyperkid123** [comment]
@elianerpereira hi. I see other PR that has the same exact content fir the hms-deplyment. Is that a duplicate?

**Comment by elianerpereira** [comment]
@Hyperkid123 thank you for noticing this. I created an incorrect folder name and could not change it in the UI. I will close this PR. Thank you!

**Comment by elianerpereira** [comment]
Sorry for the confusion.
It should contain just the [docs/quickstarts/bundlename-resource-name/bundlename-resource-name.yml’](https://github.com/RedHatInsights/quickstarts/pull/111/files#diff-5eb03b850608fdfa76cbef6ffd3eb283917987bf1ad29a368dea2733f33ea2e7)

**Review by Hyperkid123 — APPROVED** [review]

**Pull request merged**
