### PR TITLE
RHCLOUD-35506: Update openapi spec with new params

### PR DESCRIPTION
**Pull request by JetyAdam**
https://issues.redhat.com/browse/RHCLOUD-35506

### CODE REVIEW

**Comment by florkbr** [comment]
@JetyAdam just confirming - is this the result of running `make generate-spec`? https://github.com/RedHatInsights/quickstarts/blob/main/Makefile#L24

**Comment by florkbr** [comment]
@JetyAdam this will be a breaking change for anyone who uses the `bundle` param. Do we know if it is used anywhere else? It might be better to mark it deprecated and then remove it after some time has passed if we are unsure.

Past that - I believe the tests are failing in the pipeline:

```
[0.404ms] [rows:1] UPDATE `quickstarts` SET `created_at`="2024-09-30 14:04:19.861",`updated_at`="2024-09-30 14:04:19.862",`deleted_at`=NULL,`name`="rhel-quickstart",`content`="{\"tags\": \"rhel\"}" WHERE `quickstarts`.`deleted_at` IS NULL AND `id` = 5
14:04:21 --- FAIL: TestGetAll (0.01s)
14:04:21     --- FAIL: TestGetAll/should_get_all_quickstarts_with_'rbac'_application_tag (0.00s)
14:04:21         quickstarts_test.go:158: 
14:04:21             	Error Trace:	/src/mypackage/myapp/pkg/routes/quickstarts_test.go:158
14:04:21             	Error:      	Not equal: 
14:04:21             	            	expected: 2
14:04:21             	            	actual  : 1
14:04:21             	Test:       	TestGetAll/should_get_all_quickstarts_with_'rbac'_application_tag
14:04:21         quickstarts_test.go:159: 
14:04:21             	Error Trace:	/src/mypackage/myapp/pkg/routes/quickstarts_test.go:159
14:04:21             	Error:      	Not equal: 
14:04:21             	            	expected: "tagged-quickstart"
14:04:21             	            	actual  : "rbac-quickstart"
14:04:21             	            	
14:04:21             	            	Diff:
14:04:21             	            	--- Expected
14:04:21             	            	+++ Actual
14:04:21             	            	@@ -1 +1 @@
14:04:21             	            	-tagged-quickstart
14:04:21             	            	+rbac-quickstart
14:04:21             	Test:       	TestGetAll/should_get_all_quickstarts_with_'rbac'_application_tag
```

**Comment by JetyAdam** [comment]
The bundle tag is used in certain places, therefore we are keeping it.

**Comment by florkbr** [comment]
@JetyAdam looks good. FYI I created a JIRA for this and updated the PR title and description - we should try to track our work via JIRA whenever possible (and for auditing if there are any issues in the future).

**Pull request merged**
