### PR TITLE
Malware Quick Start

### PR DESCRIPTION
**Pull request by CodeDuchess**
quick start for Insights malware detection service

### CODE REVIEW

**Comment by Hyperkid123** [comment]
@RedHatInsights/platform-experience can you guys help @CodeDuchess?

**Comment by ryelo** [comment]
@CodeDuchess Can you just reverify that everything looks correct?

**Comment by CodeDuchess** [comment]
@ryelo It has had several peer reviews. So, it is good to go. Thanks.

**Review by Hyperkid123 — APPROVED** [review]

**Comment by CodeDuchess** [comment]
@Hyperkid123 @ryelo Thanks so much for your assistance with this PR! I am new to working with the console team, so I have a question. After a PR is merged, when does the new content show up in the UI? Just wanting to better understand the workflow. Thanks!

**Pull request merged**
