### PR TITLE
changed QS icon; edited wording to match other quickstarts

### PR DESCRIPTION
**Pull request by dayleparker**
Updated first quickstart:
- icon is now a rocketship as instructed by the Patternfly template
- edited some wording in 1st step to reflect wording discussed/approved by SMEs in future quickstarts that are in draft form.

Jira: https://issues.redhat.com/browse/RHCLOUD-23580

@Hyperkid123 please merge if this looks OK to you :) Thank you!

### CODE REVIEW

**Comment by dayleparker** [comment]
@Hyperkid123 - one issue - the bold text doesn't render for me in the preview tool (https://quickstarts-content-preview.surge.sh/) but I think I did it correctly. Did I miss anything? Can also wait until it's merged to see if it renders properly...

**Comment by dayleparker** [comment]
@Hyperkid123 I think all should be ready now - I replaced the book icon for the time being. :)

**Review by Hyperkid123 — APPROVED** [review]

**Pull request merged**
