### PR TITLE
added warning admonition for Azure Workaround

### PR DESCRIPTION
**Pull request by arburka**
Added a workaround link in the azure source using an admonition block

### CODE REVIEW

**Comment by arburka** [comment]
@Hyperkid123 if https://github.com/RedHatInsights/sources-ui/pull/1091 gets in, we do not need this.

**Comment by ezr-ondrej** [comment]
The sources PR is merged, but waiting for release

**Review by Hyperkid123 — APPROVED** [review]

**Comment by ezr-ondrej** [comment]
We do not need this now, we got the workaround merged! :tada:

**Comment by Hyperkid123** [comment]
@arburka @ezr-ondrej so can we just close the PR?

**Comment by ezr-ondrej** [comment]
I believe so, but I'll let @arburka close it once he wakes up :)

**Comment by arburka** [comment]
Yes, if @ezr-ondrej has a fix then we do not need to update the quickstart @Hyperkid123

**Pull request closed without merging**
