### PR TITLE
Add Conversion QS, Pre-Upgrade QS, and Edits to Pre-conversion.

### PR DESCRIPTION
**Pull request by arburka**
Added new convert qs

### CODE REVIEW

**Comment by arburka** [comment]
Hello @Hyperkid123 ! Hope you are feeling better :(

I let the content people know this is ready for them to review. If nothing gets mentioned can you take care of this early next week?

**Comment by Hyperkid123** [comment]
@arburka OFC. I think there might be a typo in s doc/metadata name. CI throws this error:
```
22:36:15 #13 0.720 Help topic validation error. Error occured in:  docs/quickstarts/insights-tasks-convert/insights-tasks-pre-conversion.yaml
22:36:15 #13 0.722 panic: open docs/quickstarts/insights-tasks-convert/insights-tasks-pre-conversion.yaml: no such file or directory
```

**Comment by arburka** [comment]
@Hyperkid123 Thank you! Fixed!

**Review by Hyperkid123 — APPROVED** [review]

**Pull request merged**
