### PR TITLE
m6-create-app-bring-source

### PR DESCRIPTION
**Pull request by missmesss**
@Hyperkid123 @ryelo This PR will contain text updates for the 3 side panels. Markdown syntax is the main concern here, I hope my humble experiments will be processed correctly in the panels.

Please, let me know if there's a way to check the screenshots without bothering you in every PR :) 
Thank you.

### CODE REVIEW

**Comment by missmesss** [comment]
Thanks so much for the preview tool @Hyperkid123, you're a magician, it helped me a lot to understand what syntax is supported.

What I was wondering about... Are there any ways to expand the syntax support? E.g. I couldn't add admonitions (or blockquotes to simulate admonitions), also blank lines are somewhat an issue (I tried 4 syntax options I found on stackoverflow, none could be processed).

My docs team is concerned a bit about Help panels looks, they could benefit a lot from some extra formatting/styling options (like blank lines for more white space, admonitions and some color) but I'm not sure we should hope for those... WDYT?

Thanks again!

**Comment by Hyperkid123** [comment]
> What I was wondering about... Are there any ways to expand the syntax support? E.g. I couldn't add admonitions (or blockquotes to simulate admonitions), also blank lines are somewhat an issue (I tried 4 syntax options I found on stackoverflow, none could be processed).

@missmesss Unfortunately that is not something I can help you with. If you require the panel extension you will have to talk to the Patternfly team. I can only help with the storage and the platform UI integration.

**Comment by missmesss** [comment]
> 

@Hyperkid123 Thanks for letting me know, it makes sense. We'll figure out how to work around some things, thanks for helping out!

**Comment by missmesss** [comment]
@Hyperkid123 The last 2 commits add all updates we hoped to publish for M6.

Please, feel free to merge if all looks good.

If some syntax (like quotes with >) break something in yaml, please, feel free to remove the greater-than signs (>) by yourself or let me know today or tomorrow, I'll remove them.

Thanks for keeping an eye on these PRs :)

**Review by Hyperkid123 — APPROVED** [review]

**Pull request merged**
