### PR TITLE
HACDOCS-264: Add Stonesoup Learn more side panel content

### PR DESCRIPTION
**Pull request by jseseCCS**
@rohitkrai03 going ahead with the new PR we talked about so that this gets merged for the "Learn more" side panel content instead of what was merged yesterday. Everything look OK?

[HACDOCS-264](https://issues.redhat.com/browse/HACDOCS-264)

### CODE REVIEW

**Review by rohitkrai03 — CHANGES_REQUESTED** [review]
@jseseCCS I think you need to rebase your branch first.Some of the changes in this PR has already been merged that is not being picked up without that rebase.

**Comment by jseseCCS** [comment]
@rohitkrai03 `git rebase upstream/main`?

**Comment by rohitkrai03** [comment]
> @rohitkrai03 `git rebase upstream/main`?

Yes.

**Comment by jseseCCS** [comment]
closing as invalid per @rohitkrai03

**Pull request closed without merging**
