### PR TITLE
Hms deployment

### PR DESCRIPTION
**Pull request by elianerpereira**
Update hms-deploy file

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
we alreasy have `docs/quickstarts/insights-launch-aws` shod we just improve that? :)

**Comment by elianerpereira** [comment]
@ezr-ondrej I was asked to create this some time ago:-)  Should this PR be closed?
Is there anything I could help with on docs/quickstarts/insights-launch-aws? Please, feel free to tag me in case anything is needed. Thank you.

**Comment by ezr-ondrej** [comment]
I believe we can close this, Any improvement in the wording and getting it more clear is welcome, but I think we are in a good spot right now, so nothing important I'd know of really :)

**Comment by elianerpereira** [comment]
Work is being done on docs/quickstarts/insights-launch-aws

**Pull request closed without merging**
